name: IMComplete
channels:
  - conda-forge
  - pytorch-lts
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - jupyterlab
  - jupytext
  - cellpose 
  - pyqtgraph
  - numba
  - scipy
  - natsort
  - tifffile==2024.8.10
  - brotlipy
  - matplotlib 
  - pandas 
  - panel 
  - opencv 
  - scikit-image 
  - ipywidgets 
  - jupyter 
  - ipykernel 
  - ipympl
  - plotly
  - ipywidgets
  - pip:
        - -e ./
        - -e ../ImcSegmentationPipeline
        - PyQt5 
        - cellpose[gui] 
        - ttkbootstrap
